### ISSUE TITLE
Do we need a preprocessor? 

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb2021_base#10]
Evaluate the benefits of using a preprocessor for CSS and other tasks.

**Comment by brookestevens** [comment]
As of now, I don't think adding a preprocessor is necessary. I think that if we choose to create our own Bootstrap themes, then we will need a preprocessor. I would recommend SCSS and use `npm` to transform the SCSS into CSS. Since the linters already use `npm` it won't be too hard to add in the `scss` packages. We can also use Github Actions to automatically build the styles for us.

**Comment by jcsparks** [comment]
Great, thanks for looking into this Brooke.  I don't think we need an ADR document for a technology that we've decided isn't necessary.  I'm going to close this ticket for now and we can revisit the preprocessor discussion if things change in the future.
